@startuml
left to right direction

actor Client
actor Caissier

rectangle "Alkatrak" {
    usecase "Deposer les articles" as UC1
    usecase "Scanner les articles" as UC1_2
    usecase "Signaler la fin de la vente" as UC2
    usecase "Choisir un mode de paiement" as UC1_2

    usecase "Signaler la fin de la vente" as UC2
    usecase "Afficher le total des achats" as UC3
    usecase "Choisir un mode de paiement" as UC1_2 
}

@enduml

