@startuml
left to right direction

actor Caissier
actor Client
actor Responsable
rectangle Centre_autorisation_multi_banques
rectangle System_gestion_stocks


rectangle "Alkatrak" {
    usecase "Scanner les articles" as UC1
    usecase "Payer" as UC3
    usecase "Appliquer un coupon rabais" as UC6
    usecase "Initialiser les caisses" as UC7
    usecase "Enregistrer la vente" as UC8
    usecase "Liquide" as UC9
    usecase "Cheque" as UC10
    usecase "Carte de credit" as UC11
    usecase "Choisir nombre d'articles" as UC12

}

Client --> UC3
UC3 --> System_gestion_stocks
Caissier --> UC1
Caissier --> UC8
UC6 .-> UC8 : <<extend>>
UC1 <-. UC12 : <<extend>>
UC8 .-> UC3 : <<include>>
UC3 <|-- UC9
UC3 <|-- UC10
UC3 <|-- UC11
UC11 -- Centre_autorisation_multi_banques



Responsable --> UC7



@enduml

