@startuml
left to right direction

actor Caissier
actor Responsable
rectangle Centre_autorisation_multi_banques
rectangle System_gestion_stocks


rectangle "Alkatrak" {
    usecase "Scanner les articles" as UC1
    usecase "Signaler la fin de la vente" as UC2
    usecase "Choisir un mode de paiement" as UC3
    usecase "Encaisser l'argent" as UC4
    usecase "Enregistrer le montant du cheque dans la caisse" as UC5
    usecase "Appliquer un coupon rabais" as UC6
    usecase "Initialiser les caisses" as UC7
    usecase "Enregistrer la vente" as UC8




}

Caissier --> UC1
Caissier --> UC2
UC3 .-> UC2 : <<include>>
UC4 --|> UC3 
UC5 --|> UC3
Centre_autorisation_multi_banques .-> UC3 : <<extend>>
UC6 .-> UC2 : <<extend>>
UC8 .-> UC3 : <<include>>
UC8 -- System_gestion_stocks




Responsable --> UC7



@enduml

